apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag-configmap
data:
  POSTGRES_USER: wallabag
  SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
  SYMFONY__ENV__DATABASE_HOST: wallabag-db.mischavandenburg.net
  SYMFONY__ENV__DATABASE_PORT: "5432"
  SYMFONY__ENV__DATABASE_NAME: wallabag
  SYMFONY__ENV__DATABASE_USER: wallabag
  SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.mischavandenburg.net"
