apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - weave-gitops-dashboard.yaml
  - cert-manager.yaml
  # - csi-secrets-store-provider-azure.yaml
