apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - commafeed
  - health-api
  # - home-assistant
  - homepage
  - linkding
  # - mealie
  # - n8n
  - pgadmin
  - shelly
  - skool
  - wallabag
  - zettelkasten-tracker
