apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n/
  - configmap.yaml
  - database.yaml
  # - scheduled-backup.yaml
  # - cloudflare.yaml
  # - networkpolicy.yaml

patches:
  - target:
      kind: SecretProviderClass
    patch: |-
      - op: replace
        path: /spec/parameters/keyvaultName
        value: k8s-homelab-production
