apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: homepage-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # kubernetes.yaml: |
        #   mode: cluster
        settings.yaml: ""
        custom.css: ""
        custom.js: ""
        bookmarks.yaml: |
          - Business:
              - KubeCraft Calendar:
                  - abbr: KC
                    href: https://calendar.google.com/calendar/u/1/r
              - Appointment Scheduling:
                  - abbr: AS
                    href: https://calendar.google.com/calendar/u/0/appointments/AcZssZ0uY58Ok_XAUTcq2whUjU7KNc3vQpxt08UAGxk=
              - Knab Boekhouding:
                  - abbr: KB
                    href: https://knab.digibtw.nl/

        services.yaml: |
          - Homelab:
            - Pi-hole:
                  href: "http://192.168.120.10:3009/admin"
                  icon: pi-hole.png
                  widget:
                      type: pihole
                      url: "http://192.168.120.10:3009"
                      # version: 6 # required if running v6 or higher, defaults to 5
                      key: {{ .piholekey }}
            - Pgadmin:
                  href: https://pgadmin.mischavandenburg.net
                  icon: pgadmin.png
            - Grafana:
                  href: http://grafana.mischavandenburg.net
                  icon: grafana.png
            - Synology:
                  href: http://192.168.120.186:5000/
                  icon: synology.png
            - Transmission:
                  href: http://192.168.120.186:3001/
                  icon: transmission.png
            - Unifi:
                  href: https://unifi.ui.com/consoles/942A6F1064FA0000000007DE81DF0000000008475267000000006579C213:1019936139/network/default/dashboard
                  description: Unifi
                  icon: unifi.png
            # - Home Assistant:
            #       href: https://ass.mischavandenburg.net
            #       description: Home Assistant
            #       icon: home-assistant.png


          - Consuming:
            - Commafeed:
                  href: http://commafeed.mischavandenburg.net
                  icon: commafeed.png
            - Hacker News:
                  href: https://news.ycombinator.com/
                  icon: commafeed.png
            - Wallabag:
                  href: http://wallabag.mischavandenburg.net
                  icon: wallabag.png

            - {{ .hiddenname01 }}:
                  href: {{ .hiddenurl01 }}
                  icon: {{ .hiddenname01 | lower }}.png

            - {{ .hiddenname02 }}:
                  href: {{ .hiddenurl02 }}
                  icon: {{ .hiddenname02 | lower }}.png

            - YouTube:
                  href: https://youtube.com
                  icon: youtube.png

          - Creating:
            - YouTube Studio:
                  href: https://studio.youtube.com
                  icon: youtube.png
            - Hypefury:
                  href: https://app.hypefury.com/
                  icon: mdi-note-text-outline-#1F93FF
            - X:
                  href: https://x.com
                  icon: x.png
            - LinkedIn:
                  href: https://linkedin.com
                  icon: linkedin.png
            - Skool:
                  href: https://www.skool.com/kubernetes-devops-cloud-3122
                  icon: mdi-school-outline-#FFF200
            - Substack:
                    href: https://mischavandenburg.substack.com
                    icon: si-substack-#FF6719

          - Misc:
            - Linkding:
                  href: https://linkding.mischavandenburg.net/bookmarks
                  icon: linkding.png
            - N8n:
                  href: https://n8n.mischavandenburg.net
                  icon: n8n.png
            - Claude:
                  href: https://claude.ai/new
                  icon: mdi-robot-excited-outline-#DE7552
            - Yr:
                    href: https://www.yr.no/nb/v%C3%A6rvarsel/daglig-tabell/2-2748413/Nederland/Noord-Holland/Purmerend%20Municipality/Purmerend
                    icon: mdi-sun-thermometer-#FFF200
                    widget:
                      type: iframe
                      name: Yr Weather
                      src: https://www.yr.no/en/content/2-2748413/card.html

        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
          - resources:
              backend: resources
              expanded: true
              cpu: true
              memory: true
          - search:
              provider: duckduckgo
              target: _blank

        docker.yaml: ""
  data:
    - secretKey: piholekey
      remoteRef:
        key: pihole-key
    - secretKey: hiddenname01
      remoteRef:
        key: hiddenname01
    - secretKey: hiddenurl01
      remoteRef:
        key: hiddenurl01
    - secretKey: hiddenname02
      remoteRef:
        key: hiddenname02
    - secretKey: hiddenurl02
      remoteRef:
        key: hiddenurl02
    # - secretKey: port
    #   remoteRef:
    #     key: synology-port
    # - secretKey: https
    #   remoteRef:
    #     key: synology-https
    # - secretKey: username
    #   remoteRef:
    #     key: synology-username
    # - secretKey: password
    #   remoteRef:
    #     key: synology-password
