apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - secret.yaml
  - serviceaccount.yaml
  - service.yaml
  - ingress.yaml
  - configmap-env.yaml
  - config-secret.yaml
  - deployment.yaml
  - clusterrole.yaml

  # The configmap for the dashboard is deployed from a private repo becuase I want to keep certain bookmarks private.
